apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: node-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-pod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: node-pod
    spec:
      containers:
        - name: node-api
          image: adarshk27r/node-api:1.0
          ports:
            - containerPort: 4000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 4000
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /readiness
              port: 4000
            initialDelaySeconds: 3
            periodSeconds: 3
