apiVersion: v1
kind: Pod
metadata:
  name: node-pod
  labels:
    name: node-pod
    app: node-pod
spec:
  containers:
    - name: node-api
      image: adarshk27r/node-api:1.0
      ports:
        - containerPort: 4000
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      livenessProbe:
        httpGet:
          path: /healthz
          port: 4000
        initialDelaySeconds: 3
        periodSeconds: 3
      readinessProbe:
        httpGet:
          path: /readiness
          port: 4000
        initialDelaySeconds: 3
        periodSeconds: 3
