apiVersion: v1
kind: Pod
metadata:
  name: node-pod
  labels:
    name: node-pod
    app: node-pod
spec:
  containers:
  - name: node-api
    image: adarshk27r/node-api:1.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 4000
